---
title: "Rapid cycleway prioritisation tool"
author: "University of Leeds"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = "..")
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r pkg, include=FALSE}
library(sf)
library(tidyverse)
library(tmap)
tmap_mode("view")
```

```{r, eval=FALSE}
# test build works before running for all:
source("code/build.R")
```

```{r}
regions = readRDS("regions_dft.Rds")
regions_centroids = sf::st_point_on_surface(regions)
regions$html_name = tolower(gsub(pattern = " |, ", replacement = "-", regions$Name))
regions$url = paste0("<a href='", regions$html_name ,"' target='_blank'>", regions$Name, "</a>")
```

```{r}
pvars = c("Name", "Level")
tm_shape(regions) + tm_polygons("Level", popup.vars = pvars) + tm_shape(regions_centroids) + tm_text("Name", size = 0.7)
```

```{r}
dn = "popupCycleways/v0.2" # dirctory name
built_regions = list.files(dn)
regions %>%
  sf::st_drop_geometry() %>%
  filter(html_name %in% built_regions) %>% 
  select(Name, Level, url) %>% 
  arrange(Name) %>% 
  DT::datatable(escape = -4)
```

```{r, eval=FALSE}

sample_to_build_regex = "west of|west y|west mid|hereford|nott|leic|manc|liv|cam"
region_names_to_build = regions %>% 
  filter(grepl(pattern = sample_to_build_regex, x = Name, ignore.case = TRUE)) %>% 
  pull(Name)
dir.create(dn)
# region_names_to_build = c("West Yorkshire", "Nottingham")
rmarkdown::render("code/index.Rmd", output_dir = dn)
# region_names_to_build = c("Greater London", "Cambridgeshire")
regions_within_names = c("Leicester", "Nottingham", "Derby", "Stoke-on-Trent")
names(regions_within_names) = c(paste0(regions_within_names[1:3], "shire"), "Staffordshire")
regions_containing_names = names(regions_within_names)
names(regions_containing_names) = regions_within_names

rn = "West of England"
for(rn in region_names_to_build) {
  region = regions %>% filter(Name == rn)
  if(rn %in% c(regions_within_names)) {
    region$geometry = sf::st_union(
      region,
      regions %>% filter(Name == regions_containing_names[rn])
      ) %>% sf::st_geometry()
  }
  t = Sys.time()
  message("Building for ", rn)
  d = file.path(dn, region$html_name)
  dir.create(d)
  region_name = region$Name
  # source("code/build.R")
  rmarkdown::render(input = "code/build.R", output_dir = d, knit_root_dir = ".")
  plot(sf::st_geometry(r_lanes_top))
  htmlwidgets::saveWidget(m_leaflet, file.path("~/cyipt/tempCycleways/", d, "m.html"))
  time_to_run = Sys.time() - t
  rmarkdown::render("code/region_index.Rmd", output_file = file.path("~/cyipt/tempCycleways/", d, "index.html"))
  message(round(time_to_run), " minutes to build ", rn)
}
```




